
server:
    port: 8080

spring:
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: ${DATASOURSE_URL}
        driver-class-name: org.h2.Driver
        user: ${DATASOURSE_USER}
        password: ${DATASOURSE_PASSWORD}
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true


flyway:
    user: ${DATASOURSE_USER}
    password: ${DATASOURSE_PASSWORD}
    schemas: investment
    url: ${DATASOURSE_URL}
    locations: classpath:db/migration



